export const LOGICAL_WIDTH = 384;
export const LOGICAL_HEIGHT = 216;
export const FIXED_STEP = 1 / 120;
export const MAX_FRAME_DELTA = 0.1;

export const TUNING = {
  runDuration: 78,
  entryGrace: 8,
  maxWipeouts: 3,
  speed: 72,
  maxSpeed: 138,
  carveAcceleration: 3.35,
  carveFriction: 4.8,
  faceEdgeBounce: 0.28,
  wavePush: 13.5,
  curlSpeed: 2.35,
  curlCatchDelay: 0.58,
  pumpStrength: 17,
  pumpChargeRate: 1.55,
  launchForce: 112,
  gravity: 176,
  rotationAcceleration: 13.6,
  angularDrag: 1.65,
  airControl: 0.92,
  landingTolerance: 0.46,
  perfectTolerance: 0.115,
  landingCoyote: 0.095,
  launchCoyote: 0.11,
  wipeoutThreshold: 1.18,
  cameraResponse: 5.8,
  juiceIntensity: 1,
  scoreSpeed: 0.22,
  scorePocket: 1.05,
  scoreFlow: 0.38,
  scoreAir: 1.25,
};

export const BOARDS = {
  foamPuff: {
    id: "foamPuff",
    name: "Foam Puff",
    tagline: "Soft landings, mellow spins.",
    description: "Forgiving and steady. Keeps its composure when your paws do not.",
    color: "#ffd66b",
    accent: "#ef6f6c",
    acceleration: 0.96,
    maxSpeed: 0.93,
    grip: 1.08,
    pump: 0.92,
    launch: 0.94,
    rotation: 0.84,
    airControl: 1.08,
    landing: 1.28,
    recovery: 1.24,
    style: 0.94,
    shape: "puff",
    specialty: "RECOVERY + QUICK GRABS",
    recommendation: "BEGINNER",
    signature: { speed: 1.14, score: 0.9, risk: 0.78 },
    stats: { speed: 2, carve: 3, pump: 3, pop: 3, spin: 2, landing: 5 },
  },
  mangoFish: {
    id: "mangoFish",
    name: "Mango Fish",
    tagline: "Quick rails, pocket hungry.",
    description: "Fast turns and sharp lines. Best when the curl is breathing on your tail.",
    color: "#ff9f45",
    accent: "#4c5f9e",
    acceleration: 1.12,
    maxSpeed: 1.04,
    grip: 1.18,
    pump: 1.08,
    launch: 1,
    rotation: 1.08,
    airControl: 1,
    landing: 0.94,
    recovery: 0.96,
    style: 1.08,
    shape: "fish",
    specialty: "SNAPS + COMBO CHAINS",
    recommendation: "TECHNICAL",
    signature: { speed: 0.9, score: 1.04, risk: 1.08 },
    stats: { speed: 4, carve: 5, pump: 4, pop: 3, spin: 5, landing: 2 },
  },
  moonLog: {
    id: "moonLog",
    name: "Moon Log",
    tagline: "Heavy glide, enormous pop.",
    description: "Carries speed like a tide. Slow to correct, glorious above the lip.",
    color: "#c9b6ff",
    accent: "#214c6b",
    acceleration: 0.88,
    maxSpeed: 1.12,
    grip: 0.86,
    pump: 1.04,
    launch: 1.22,
    rotation: 0.76,
    airControl: 0.8,
    landing: 1.02,
    recovery: 0.88,
    style: 1.14,
    shape: "log",
    specialty: "BIG POP + LONG HOLDS",
    recommendation: "EXPERT",
    signature: { speed: 1.18, score: 1.28, risk: 1.2 },
    stats: { speed: 5, carve: 2, pump: 4, pop: 5, spin: 2, landing: 3 },
  },
};

export const CONDITIONS = {
  goldenCoast: {
    id: "goldenCoast",
    name: "Golden Coast",
    shortName: "GOLDEN",
    tagline: "Sunlit seams and warm offshore glass.",
    musicMode: "sunset",
  },
  twilightGlass: {
    id: "twilightGlass",
    name: "Twilight Glass",
    shortName: "TWILIGHT",
    tagline: "Violet horizon, luminous cold-water lines.",
    musicMode: "night",
  },
  stormbreak: {
    id: "stormbreak",
    name: "Stormbreak",
    shortName: "STORM",
    tagline: "Electric squalls and a hard silver pocket.",
    musicMode: "storm",
  },
};

export const SCORE = {
  ridePerSecond: 20,
  speedThreshold: 82,
  pocketStart: 0.42,
  pocketMax: 2.4,
  carveMinVelocity: 0.28,
  carvePoints: 34,
  launchBase: 45,
  airHeightScale: 1.8,
  halfRotation: 95,
  fullRotation: 260,
  extraRotation: 175,
  grab: 120,
  perfectLanding: 240,
  cleanLanding: 95,
  wobbleSave: 55,
  repeatDecay: 0.58,
  comboStep: 0.18,
  comboMax: 4.2,
};

export const DEFAULT_SETTINGS = {
  music: 0.58,
  effects: 0.78,
  waveAudio: 0.52,
  reducedMotion: false,
  screenShake: 0.7,
  reducedFlash: true,
  highContrast: false,
  steeringAssist: false,
  landingAssist: false,
  touchControls: true,
  waveReadAssist: "full",
};

export const SAVE_KEY = "kaki-surf-meta-v1";

// Canonical visual identities from Kitty Kaki Survivors. These paths are
// integration/provenance metadata only: the standalone surf build does not
// fetch or ship the GLBs. A future host adapter can resolve an avatar id to its
// native model while the 2D game selects a curated, hand-cleaned sprite set.
export const SURVIVORS_HERO_SOURCES = {
  version: 1,
  project: "kitty-kaki-survivors",
  basePath: "assets/breakroom/",
  primaryAvatarId: "kitty",
  runtimePolicy: "reference-only",
  avatars: {
    kitty: { name: "Kitty Kaki", glb: "tower-castle-plain.glb", role: "primary" },
    sote: { name: "Sote", glb: "sote.glb" },
    cowboy: { name: "CowboyKaki", glb: "cowboykaki.glb" },
    pipes: { name: "Pipes", glb: "pipes.glb" },
    bomdia: { name: "Bom Dia", glb: "bomdia.glb" },
    mothman: { name: "Mothman", glb: "mothman.glb" },
    camper: { name: "Camper", glb: "camper.glb" },
    space: { name: "Space Kitty", glb: "spacekitty.glb" },
    radcat: { name: "Radcat", glb: "radcat.glb" },
    mona: { name: "Mona", glb: "mona.glb" },
    bezelbug: { name: "BezelBug", glb: "bezelbug.glb" },
    rocker: { name: "RockerKaki", glb: "rockerkaki.glb" },
    borgirboss: { name: "BorgirBoss", glb: "borgirboss.glb" },
    rune_kitten: { name: "Rune Kitten", glb: "tower-castle-plain.glb", donorTint: "#7fffe4" },
    mire_kitten: { name: "Mire Kitten", glb: "tower-castle-plain.glb", donorTint: "#4a7a4a" },
    shroud_kitten: { name: "Shroud Kitten", glb: "tower-castle-plain.glb", donorTint: "#6a4a8a" },
  },
};

export const COSMETIC_MANIFEST = {
  version: 2,
  hero: "kittyKaki",
  sourceIdentity: {
    project: SURVIVORS_HERO_SOURCES.project,
    avatarId: SURVIVORS_HERO_SOURCES.primaryAvatarId,
    glb: SURVIVORS_HERO_SOURCES.avatars.kitty.glb,
  },
  allowedCombinations: ["kittyKaki:bluePlush:classicFace:beachHoodie"],
  traits: {
    species: [{ id: "kittyKaki", label: "Kitty Kaki", rarity: "hero" }],
    furPalette: [
      { id: "bluePlush", label: "Blueberry Plush", colors: ["#214c6b", "#2f78a2", "#70c1d4"] },
    ],
    face: [{ id: "classicFace", label: "Calm Cat", expressionSet: "calm-cat-v1" }],
    ears: [{ id: "softPoints", label: "Soft Points" }],
    tail: [{ id: "bobTail", label: "Bob Tail" }],
    outfit: [{ id: "beachHoodie", label: "Night Beach Hoodie", colors: ["#1c1833", "#f4eee1"] }],
    accessory: [{ id: "none", label: "No Accessory" }],
    boards: Object.values(BOARDS).map(({ id, name }) => ({ id, label: name })),
    boardPattern: [{ id: "sunstripe", label: "Sunstripe" }],
    trail: [{ id: "starFoam", label: "Star Foam" }],
    victoryPose: [{ id: "tinyPaw", label: "Tiny Paw Triumph" }],
  },
};

export const PALETTES = {
  standard: {
    ink: "#17172b",
    deepInk: "#0d1025",
    skyTop: "#5aa7cb",
    sky: "#9bd7d7",
    sun: "#fff0a7",
    haze: "#e6f0cf",
    distant: "#3e7690",
    waterDeep: "#184f72",
    water: "#247fa2",
    waterLight: "#51b7bd",
    crest: "#b9e6d3",
    foam: "#f7f2d7",
    foamShade: "#9dd9c8",
    danger: "#ed6a5a",
    gold: "#ffd166",
    violet: "#8a78c2",
    plushDark: "#214c6b",
    plush: "#2f78a2",
    plushLight: "#70c1d4",
    hoodie: "#1c1833",
    face: "#f4dfc8",
    cheek: "#ef9a9a",
    white: "#fff8e7",
  },
  contrast: {
    ink: "#05020d",
    deepInk: "#000000",
    skyTop: "#4b96d1",
    sky: "#a8e5e2",
    sun: "#fff26b",
    haze: "#ffffff",
    distant: "#235c86",
    waterDeep: "#073d70",
    water: "#007aa8",
    waterLight: "#19d0c8",
    crest: "#afffe0",
    foam: "#ffffff",
    foamShade: "#63d8bd",
    danger: "#ff3e35",
    gold: "#ffe24d",
    violet: "#ad8cff",
    plushDark: "#092f59",
    plush: "#1389c4",
    plushLight: "#8aeaff",
    hoodie: "#080515",
    face: "#fff1d4",
    cheek: "#ff8d98",
    white: "#ffffff",
  },
  twilightGlass: {
    ink: "#17142e",
    deepInk: "#09091c",
    skyTop: "#554c91",
    sky: "#9a8fc0",
    sun: "#ffd19a",
    haze: "#cfbdd4",
    distant: "#41557d",
    waterDeep: "#102f56",
    water: "#235b83",
    waterLight: "#54a3a8",
    crest: "#9be0cf",
    foam: "#e9ead8",
    foamShade: "#73bfc0",
    danger: "#f07382",
    gold: "#ffd27a",
    violet: "#b49bf1",
    plushDark: "#1a385e",
    plush: "#367da7",
    plushLight: "#78cbd4",
    hoodie: "#151129",
    face: "#f0d6c1",
    cheek: "#ec93a3",
    white: "#f6f1e4",
  },
  stormbreak: {
    ink: "#101928",
    deepInk: "#060b14",
    skyTop: "#34475b",
    sky: "#718c98",
    sun: "#dff3d0",
    haze: "#b7cbc8",
    distant: "#314d5c",
    waterDeep: "#0b3b50",
    water: "#16677a",
    waterLight: "#43a6a0",
    crest: "#a8dfcf",
    foam: "#edf0d8",
    foamShade: "#7dc8b5",
    danger: "#ff715f",
    gold: "#e9e576",
    violet: "#8f90cb",
    plushDark: "#173c59",
    plush: "#307b9e",
    plushLight: "#78c8cf",
    hoodie: "#121b2d",
    face: "#ead6c2",
    cheek: "#e78e91",
    white: "#f3f2dc",
  },
};
