export const LOGICAL_WIDTH = 384;
export const LOGICAL_HEIGHT = 216;
export const GAME_VERSION = "2.0.2";
export const FIXED_STEP = 1 / 120;
export const MAX_FRAME_DELTA = 0.1;

export const DEFAULT_WAVE_STYLE_ID = "classic";

export const DEFAULT_RUN_MODE_ID = "endless";
export const SCORE_ATTACK_DURATION = 78;

export const RUN_MODES = Object.freeze({
  endless: Object.freeze({
    id: "endless",
    name: "Endless Surf",
    shortName: "ENDLESS",
    tagline: "Three paws. The break keeps building.",
    timed: false,
    startLabel: "CHASE THE HORIZON",
    startHint: "3 PAWS / NO CLOCK",
  }),
  scoreAttack: Object.freeze({
    id: "scoreAttack",
    name: "Score Attack",
    shortName: "78 SEC",
    tagline: "Bank the biggest score before the horn.",
    timed: true,
    duration: SCORE_ATTACK_DURATION,
    startLabel: "START SCORE ATTACK",
    startHint: "78 SECONDS",
  }),
});

/**
 * Condition-owned wave profiles. GameplayWave is the canonical consumer of
 * `surface`, `power`, `threat`, and `pocket`; the renderer may consume the
 * read-only `barrel` and `projection` values without recreating gameplay math.
 */
export const WAVE_STYLES = Object.freeze({
  classic: Object.freeze({
    id: "classic",
    // Golden Coast and Stormbreak share the production long-break compositor
    // until their level-specific silhouettes are authored. Keeping one
    // renderer prevents the retired mini-curl/white-shelf path from returning.
    renderer: "heroBarrel",
    bounds: Object.freeze({
      // Every production condition uses the same California Games-style
      // forward dead zone. Kaki crosses the face before forward overflow
      // scrolls the break; the right edge never hard-stops board motion.
      ridingX: Object.freeze([76, 350]),
      airX: Object.freeze([58, 352]),
      cameraX: Object.freeze([76, 324]),
    }),
    surface: Object.freeze({
      crestBase: 75,
      broadAmplitude: 3.5,
      broadXFrequency: 0.015,
      broadTravelFrequency: 0.003,
      detailAmplitude: 1.25,
      detailXFrequency: 0.043,
      detailTimeFrequency: 0.62,
      faceDepthBase: 102,
      faceDepthAmplitude: 5,
      faceDepthXFrequency: 0.021,
      faceEaseLinear: 0.88,
      faceEaseQuadratic: 0.12,
    }),
    power: Object.freeze({
      baseFace: 0.405,
      broadAmplitude: 0.024,
      broadXFrequency: 0.018,
      broadTravelFrequency: 0.0007,
      pulseAmplitude: 0.009,
      pulseXFrequency: 0.006,
      pulseTimeFrequency: 0.11,
      pressureShift: 0.022,
      minFace: 0.31,
      maxFace: 0.49,
    }),
    threat: Object.freeze({
      // Start the visible breaking edge at x=30 (17 + 13 contact offset),
      // leaving almost the full face available before the barrel catches up.
      initialCurlX: 17,
      proximityNearGap: 24,
      proximityFarGap: 156,
      temporalPressureScale: 0.82,
    }),
    pocket: Object.freeze({
      nearOffset: 14,
      span: 126,
      contactOffset: 13,
    }),
    barrel: Object.freeze({
      stageNames: Object.freeze(["swell", "pitch", "curl", "impact"]),
      stageThresholds: Object.freeze([0.18, 0.54, 0.86]),
      growStart: 0.18,
      growEnd: 1,
      apertureStart: 0.36,
      apertureFull: 0.68,
      closeStart: 0.86,
      closeEnd: 1,
      closedAperture: 0.18,
      outerRadiusX: Object.freeze([48, 126]),
      outerRadiusY: Object.freeze([28, 78]),
      apertureRadiusX: Object.freeze([16, 45]),
      apertureRadiusY: Object.freeze([12, 40]),
      lipDrop: Object.freeze([8, 35]),
      shoulderReach: Object.freeze([68, 132]),
    }),
    projection: Object.freeze({
      horizonY: 78,
      depthShear: 0,
      fanShear: 0,
      depthDrop: 0,
      fanDrop: 0,
    }),
  }),
  heroBarrel: Object.freeze({
    id: "heroBarrel",
    renderer: "heroBarrel",
    bounds: Object.freeze({
      // The long level is a real side scroller: Kaki may use nearly the full
      // face before the camera begins following forward. The camera never
      // chases a cutback back toward the curl; Kaki crosses the screen first.
      ridingX: Object.freeze([50, 350]),
      airX: Object.freeze([50, 352]),
      cameraX: Object.freeze([74, 316]),
    }),
    surface: Object.freeze({
      // The reference horizon is y=78..80, the sustainable ride band is
      // y=136..150, and the foreground trough terminates around y=194.
      crestBase: 78,
      broadAmplitude: 2.2,
      broadXFrequency: 0.011,
      broadTravelFrequency: 0.0018,
      detailAmplitude: 0.55,
      detailXFrequency: 0.031,
      detailTimeFrequency: 0.36,
      faceDepthBase: 116,
      faceDepthAmplitude: 4,
      faceDepthXFrequency: 0.015,
      faceEaseLinear: 0.8,
      faceEaseQuadratic: 0.2,
    }),
    power: Object.freeze({
      baseFace: 0.59,
      broadAmplitude: 0.022,
      broadXFrequency: 0.014,
      broadTravelFrequency: 0.00045,
      pulseAmplitude: 0.007,
      pulseXFrequency: 0.0045,
      pulseTimeFrequency: 0.075,
      pressureShift: 0.03,
      minFace: 0.53,
      maxFace: 0.66,
    }),
    threat: Object.freeze({
      // -66 + the 96 px pitched-lip offset places first contact at x=30.
      initialCurlX: -66,
      // Grow the hero barrel while it is still readable, then let the existing
      // contact delay own the actual catch instead of hiding a larger hitbox.
      proximityNearGap: 10,
      proximityFarGap: 100,
      temporalPressureScale: 0.84,
      contactOrigin: true,
      // The barrel must visibly travel during the protected opening. Curl
      // collision remains disabled by `curlGrace`, but the shot no longer
      // appears frozen until the first wipeout consumes that clock.
      openingSpeed: 6.2,
      cameraCoupled: true,
      // Screen-space pursuit is faster than the classic fixed-frame threat,
      // because a fast rider can now advance the camera and push the barrel
      // completely offscreen. Escalation eventually closes that earned lead.
      maxSpeed: 38,
      maxRelief: 0.34,
    }),
    pocket: Object.freeze({
      nearOffset: 0,
      span: 112,
      // Curl state is the rear shoulder. The actual pitching lip reaches
      // forward into the playable composition and owns collision at this
      // single visible offset.
      contactOffset: 96,
      contactOrigin: true,
    }),
    barrel: Object.freeze({
      // Six readable beats are shared by simulation QA and the renderer. The
      // final collapse pose is further eased by the player's curl contact
      // timer, so contact does not pop directly to a closed silhouette.
      stageNames: Object.freeze(["gather", "pitch", "open", "deep", "hero", "collapse"]),
      stageThresholds: Object.freeze([0.22, 0.44, 0.68, 0.88, 0.98]),
      growStart: 0.08,
      growEnd: 0.9,
      apertureStart: 0.24,
      apertureFull: 0.58,
      closeStart: 0.86,
      closeEnd: 1,
      // Even the danger frame keeps genuine negative space through the tube.
      closedAperture: 0.34,
      outerRadiusX: Object.freeze([54, 156]),
      outerRadiusY: Object.freeze([32, 112]),
      apertureRadiusX: Object.freeze([18, 76]),
      apertureRadiusY: Object.freeze([14, 62]),
      lipDrop: Object.freeze([8, 38]),
      shoulderReach: Object.freeze([76, 212]),
    }),
    projection: Object.freeze({
      horizonY: 79,
      depthShear: 50,
      fanShear: 14,
      depthDrop: 10,
      fanDrop: 8,
    }),
  }),
});

export const TUNING = {
  runDuration: SCORE_ATTACK_DURATION,
  endlessSetDuration: 36,
  endlessMaxSet: 7,
  endlessThreatStart: 0.82,
  endlessThreatStep: 0.12,
  endlessScoreStep: 0.08,
  endlessDistanceScale: 0.25,
  entryGrace: 8,
  maxWipeouts: 3,
  speed: 76,
  maxSpeed: 144,
  carveAcceleration: 3.65,
  carveFriction: 4,
  faceEdgeBounce: 0.28,
  downhillAcceleration: 104,
  uphillSpeedCost: 40,
  rideEnergyDrag: 2.4,
  traverseDrive: 3.2,
  // A committed cutback should draw a readable arc instead of snapping the
  // presentation direction as soon as the velocity crosses zero.
  reversalCommitTime: 0.3,
  reversalCommitSpeed: 7,
  reversalScrub: 22,
  wavePush: 15.5,
  // Turbo is an earned overdrive: one full tank lasts just under three
  // seconds, raises the board envelope by 14%, and is refilled only when an
  // aerial trick is actually banked through a clean or perfect landing.
  turboStartCharge: 1,
  turboDrainPerSecond: 0.36,
  turboAcceleration: 62,
  turboSpeedCapMultiplier: 1.14,
  turboOverdriveBuild: 11,
  turboOverdriveDecay: 2.6,
  turboTrickBaseRefill: 0.18,
  turboTrickEntryRefill: 0.12,
  turboSpinHalfTurnRefill: 0.035,
  turboPerfectRefillMultiplier: 1.15,
  turboRepeatRefillFloor: 0.35,
  turboWipeoutLoss: 0.25,
  curlSpeed: 2.35,
  curlCatchDelay: 0.58,
  curlGrace: 8,
  curlRampEnd: 72,
  curlThreatMaxSpeed: 10.8,
  curlSkillRelief: 0.46,
  curlSpeedRelief: 0.18,
  curlMaxRelief: 0.58,
  curlReliefSpeedStart: 94,
  curlReliefSpeedEnd: 126,
  curlRespawnRetreat: 42,
  curlRespawnSafeX: 90,
  tubeEntryRisk: 0.58,
  tubeHoldRisk: 0.5,
  tubeEntryFaceMin: 0.16,
  tubeEntryFaceMax: 0.76,
  tubeHoldFaceMin: 0.12,
  tubeHoldFaceMax: 0.82,
  tubeExitGrace: 0.12,
  tubeCleanExitTime: 0.45,
  tubeSteeringScale: 0.46,
  tubeSpeedPushScale: 0.08,
  pumpStrength: 18.5,
  pumpChargeRate: 1.55,
  pumpMinCharge: 0.28,
  pumpMinEfficiency: 0.15,
  pumpUpwardIntent: 0.35,
  pumpReleaseFaceVelocity: 0.08,
  pumpCooldown: 0.34,
  pumpFlowGain: 0.055,
  skillMomentumDecay: 0.065,
  pumpSkillGain: 0.11,
  carveSkillGain: 0.08,
  carveArcMinDuration: 0.18,
  carveArcMinExcursion: 0.075,
  carveArcMinPeakVelocity: 0.32,
  carveArcPauseReset: 0.35,
  reversalSkillGain: 0.08,
  landingSkillGain: 0.18,
  flowEventHold: 0.9,
  flowPassiveDecay: 0.055,
  flowStallDecay: 0.12,
  flowLineSustainStart: 0.18,
  flowLineSustainFull: 0.82,
  flowLineSustainLimit: 0.75,
  rideSpeedResponse: 0.82,
  waveMomentumBuild: 1.9,
  waveMomentumDecay: 0.55,
  waveMomentumPumpGain: 0.14,
  offLineSpeedHeadroom: 26,
  lateralResponse: 12,
  lateralCoast: 3,
  sideScrollGlideBase: 9,
  sideScrollGlideSpeed: 0.09,
  sideScrollSteerBase: 20,
  sideScrollSteerSpeed: 0.1,
  sideScrollMaxSpeed: 52,
  launchForce: 112,
  gravity: 176,
  rotationAcceleration: 13.6,
  angularDrag: 1.65,
  airControl: 0.92,
  landingTolerance: 0.46,
  perfectTolerance: 0.115,
  landingCoyote: 0.095,
  launchCoyote: 0.11,
  simpleAutoLevelStart: 18,
  simpleTrickBuffer: 0.34,
  simpleGrabHold: 0.115,
  perfectLandingCarry: 0.58,
  cleanLandingCarry: 0.4,
  wobbleLandingCarry: 0.18,
  wipeoutThreshold: 1.18,
  cameraResponse: 5.8,
  juiceIntensity: 1,
  scoreSpeed: 0.22,
  scorePocket: 1.05,
  scoreFlow: 0.38,
  scoreAir: 1.25,
};

export const BOARDS = {
  foamPuff: {
    id: "foamPuff",
    name: "Foam Puff",
    tagline: "Soft landings, mellow spins.",
    description: "Forgiving and steady. Keeps its composure when your paws do not.",
    color: "#ffd66b",
    accent: "#ef6f6c",
    acceleration: 0.96,
    maxSpeed: 0.93,
    grip: 1.08,
    pump: 0.92,
    launch: 0.94,
    rotation: 0.84,
    airControl: 1.08,
    landing: 1.28,
    recovery: 1.24,
    simpleAutoLevel: 1.35,
    style: 0.94,
    shape: "puff",
    specialty: "RECOVERY + QUICK GRABS",
    recommendation: "BEGINNER",
    signature: { speed: 1.14, score: 0.9, risk: 0.78 },
    stats: { speed: 2, carve: 3, pump: 3, pop: 3, spin: 2, landing: 5 },
  },
  mangoFish: {
    id: "mangoFish",
    name: "Mango Fish",
    tagline: "Quick rails, pocket hungry.",
    description: "Fast turns and sharp lines. Best when the curl is breathing on your tail.",
    color: "#ff9f45",
    accent: "#4c5f9e",
    acceleration: 1.12,
    maxSpeed: 1.04,
    grip: 1.18,
    pump: 1.08,
    launch: 1,
    rotation: 1.08,
    airControl: 1,
    landing: 0.94,
    recovery: 0.96,
    simpleAutoLevel: 0.9,
    style: 1.08,
    shape: "fish",
    specialty: "SNAPS + COMBO CHAINS",
    recommendation: "TECHNICAL",
    signature: { speed: 0.9, score: 1.04, risk: 1.08 },
    stats: { speed: 4, carve: 5, pump: 4, pop: 3, spin: 5, landing: 2 },
  },
  moonLog: {
    id: "moonLog",
    name: "Moon Log",
    tagline: "Heavy glide, enormous pop.",
    description: "Carries speed like a tide. Slow to correct, glorious above the lip.",
    color: "#c9b6ff",
    accent: "#214c6b",
    acceleration: 0.88,
    maxSpeed: 1.12,
    grip: 0.86,
    pump: 1.04,
    launch: 1.22,
    rotation: 0.76,
    airControl: 0.8,
    landing: 1.02,
    recovery: 0.88,
    simpleAutoLevel: 0.5,
    style: 1.14,
    shape: "log",
    specialty: "BIG POP + LONG HOLDS",
    recommendation: "EXPERT",
    signature: { speed: 1.18, score: 1.28, risk: 1.2 },
    stats: { speed: 5, carve: 2, pump: 4, pop: 5, spin: 2, landing: 3 },
  },
};

export const CONDITIONS = {
  goldenCoast: {
    id: "goldenCoast",
    name: "Golden Coast",
    shortName: "GOLDEN",
    tagline: "Sunlit seams and warm offshore glass.",
    musicMode: "sunset",
    waveStyle: "classic",
  },
  twilightGlass: {
    id: "twilightGlass",
    name: "Twilight Glass",
    shortName: "TWILIGHT",
    tagline: "Violet horizon, luminous cold-water lines.",
    musicMode: "night",
    waveStyle: "heroBarrel",
  },
  stormbreak: {
    id: "stormbreak",
    name: "Stormbreak",
    shortName: "STORM",
    tagline: "Electric squalls and a hard silver pocket.",
    musicMode: "storm",
    waveStyle: "classic",
  },
};

export const SCORE = {
  ridePerSecond: 20,
  speedThreshold: 82,
  pocketStart: 0.42,
  pocketMax: 2.4,
  carveMinVelocity: 0.28,
  carvePoints: 34,
  launchBase: 45,
  airHeightScale: 1.8,
  halfRotation: 95,
  fullRotation: 260,
  extraRotation: 175,
  grab: 120,
  perfectLanding: 240,
  cleanLanding: 95,
  wobbleSave: 55,
  repeatDecay: 0.58,
  comboStep: 0.18,
  comboMax: 4.2,
  switchTakeoff: 80,
  switchLanding: 135,
  tubeStylePerSecond: 58,
};

export const DEFAULT_SETTINGS = {
  muted: false,
  music: 0.58,
  effects: 0.78,
  waveAudio: 0.52,
  reducedMotion: false,
  screenShake: 0.7,
  reducedFlash: true,
  highContrast: false,
  steeringAssist: false,
  landingAssist: false,
  touchControls: true,
  waveReadAssist: "full",
  controlMode: "simple",
};

export const SAVE_KEY = "kaki-surf-meta-v1";

// Canonical visual identities from Kitty Kaki Survivors. These paths are
// integration/provenance metadata only: the standalone surf build does not
// fetch or ship the GLBs. A future host adapter can resolve an avatar id to its
// native model while the 2D game selects a curated, hand-cleaned sprite set.
export const SURVIVORS_HERO_SOURCES = {
  version: 1,
  project: "kitty-kaki-survivors",
  basePath: "assets/breakroom/",
  primaryAvatarId: "kitty",
  runtimePolicy: "reference-only",
  avatars: {
    kitty: { name: "Kitty Kaki", glb: "tower-castle-plain.glb", role: "primary" },
    sote: { name: "Sote", glb: "sote.glb" },
    cowboy: { name: "CowboyKaki", glb: "cowboykaki.glb" },
    pipes: { name: "Pipes", glb: "pipes.glb" },
    bomdia: { name: "Bom Dia", glb: "bomdia.glb" },
    mothman: { name: "Mothman", glb: "mothman.glb" },
    camper: { name: "Camper", glb: "camper.glb" },
    space: { name: "Space Kitty", glb: "spacekitty.glb" },
    radcat: { name: "Radcat", glb: "radcat.glb" },
    mona: { name: "Mona", glb: "mona.glb" },
    bezelbug: { name: "BezelBug", glb: "bezelbug.glb" },
    rocker: { name: "RockerKaki", glb: "rockerkaki.glb" },
    borgirboss: { name: "BorgirBoss", glb: "borgirboss.glb" },
    rune_kitten: { name: "Rune Kitten", glb: "tower-castle-plain.glb", donorTint: "#7fffe4" },
    mire_kitten: { name: "Mire Kitten", glb: "tower-castle-plain.glb", donorTint: "#4a7a4a" },
    shroud_kitten: { name: "Shroud Kitten", glb: "tower-castle-plain.glb", donorTint: "#6a4a8a" },
  },
};

export const COSMETIC_MANIFEST = {
  version: 2,
  hero: "kittyKaki",
  sourceIdentity: {
    project: SURVIVORS_HERO_SOURCES.project,
    avatarId: SURVIVORS_HERO_SOURCES.primaryAvatarId,
    glb: SURVIVORS_HERO_SOURCES.avatars.kitty.glb,
  },
  allowedCombinations: ["kittyKaki:bluePlush:classicFace:beachHoodie"],
  traits: {
    species: [{ id: "kittyKaki", label: "Kitty Kaki", rarity: "hero" }],
    furPalette: [
      { id: "bluePlush", label: "Blueberry Plush", colors: ["#214c6b", "#2f78a2", "#70c1d4"] },
    ],
    face: [{ id: "classicFace", label: "Calm Cat", expressionSet: "calm-cat-v1" }],
    ears: [{ id: "softPoints", label: "Soft Points" }],
    tail: [{ id: "bobTail", label: "Bob Tail" }],
    outfit: [{ id: "beachHoodie", label: "Night Beach Hoodie", colors: ["#1c1833", "#f4eee1"] }],
    accessory: [{ id: "none", label: "No Accessory" }],
    boards: Object.values(BOARDS).map(({ id, name }) => ({ id, label: name })),
    boardPattern: [{ id: "sunstripe", label: "Sunstripe" }],
    trail: [{ id: "starFoam", label: "Star Foam" }],
    victoryPose: [{ id: "tinyPaw", label: "Tiny Paw Triumph" }],
  },
};

export const PALETTES = {
  standard: {
    ink: "#17172b",
    deepInk: "#0d1025",
    skyTop: "#5aa7cb",
    sky: "#9bd7d7",
    sun: "#fff0a7",
    haze: "#e6f0cf",
    distant: "#3e7690",
    waterDeep: "#184f72",
    water: "#247fa2",
    waterLight: "#51b7bd",
    crest: "#b9e6d3",
    foam: "#f7f2d7",
    foamShade: "#9dd9c8",
    danger: "#ed6a5a",
    gold: "#ffd166",
    violet: "#8a78c2",
    plushDark: "#214c6b",
    plush: "#2f78a2",
    plushLight: "#70c1d4",
    hoodie: "#1c1833",
    face: "#f4dfc8",
    cheek: "#ef9a9a",
    white: "#fff8e7",
  },
  contrast: {
    ink: "#05020d",
    deepInk: "#000000",
    skyTop: "#4b96d1",
    sky: "#a8e5e2",
    sun: "#fff26b",
    haze: "#ffffff",
    distant: "#235c86",
    waterDeep: "#073d70",
    water: "#007aa8",
    waterLight: "#19d0c8",
    crest: "#afffe0",
    foam: "#ffffff",
    foamShade: "#63d8bd",
    danger: "#ff3e35",
    gold: "#ffe24d",
    violet: "#ad8cff",
    plushDark: "#092f59",
    plush: "#1389c4",
    plushLight: "#8aeaff",
    hoodie: "#080515",
    face: "#fff1d4",
    cheek: "#ff8d98",
    white: "#ffffff",
  },
  twilightGlass: {
    ink: "#0b1630",
    deepInk: "#091326",
    skyTop: "#554c91",
    sky: "#9a8fc0",
    sun: "#ffd19a",
    haze: "#cfbdd4",
    distant: "#41557d",
    waterDeep: "#102a56",
    water: "#1f6488",
    waterLight: "#48c4c9",
    crest: "#62e0d8",
    foam: "#eef9f4",
    foamShade: "#a8dfe0",
    danger: "#f07382",
    gold: "#ffd27a",
    violet: "#b49bf1",
    plushDark: "#1a385e",
    plush: "#367da7",
    plushLight: "#78cbd4",
    hoodie: "#151129",
    face: "#f0d6c1",
    cheek: "#ec93a3",
    white: "#f6f1e4",
  },
  stormbreak: {
    ink: "#101928",
    deepInk: "#060b14",
    skyTop: "#34475b",
    sky: "#718c98",
    sun: "#dff3d0",
    haze: "#b7cbc8",
    distant: "#314d5c",
    waterDeep: "#0b3b50",
    water: "#16677a",
    waterLight: "#43a6a0",
    crest: "#a8dfcf",
    foam: "#edf0d8",
    foamShade: "#7dc8b5",
    danger: "#ff715f",
    gold: "#e9e576",
    violet: "#8f90cb",
    plushDark: "#173c59",
    plush: "#307b9e",
    plushLight: "#78c8cf",
    hoodie: "#121b2d",
    face: "#ead6c2",
    cheek: "#e78e91",
    white: "#f3f2dc",
  },
};
