const SCENES = [
  ["menu", "Production menu and board cards", "wide"],
  ["results", "Results and run highlights", "wide"],
  ["settingsSimple", "Settings / Simple selected", "wide", "access"],
  ["settingsAdvanced", "Settings / Advanced selected", "wide", "access"],
  ["simpleKeyboard", "Simple Controls / keyboard", "wide", "access"],
  ["simpleGamepad", "Simple Controls / gamepad", "wide", "access"],
  ["neutral", "Neutral right-hand ride"],
  ["leftTravel", "Left travel / switch stance"],
  ["rightTravel", "Right travel"],
  ["reversal", "Committed deep cutback", "", "perfect"],
  ["downhill", "Downhill tuck / physical speed", "", "perfect"],
  ["curlEarly", "Incoming curl / early darkening"],
  ["curlFolding", "Incoming curl / folding lip"],
  ["curlImpact", "Incoming curl / foam impact", "", "danger"],
  ["curlDanger", "Incoming curl / close danger", "", "danger"],
  ["heroGather-twilightGlass", "Twilight hero barrel / gather"],
  ["heroPitch-twilightGlass", "Twilight hero barrel / pitch"],
  ["heroOpen-twilightGlass", "Twilight hero barrel / open", "", "perfect"],
  ["heroDeep-twilightGlass", "Twilight hero barrel / deep", "", "perfect"],
  ["heroMax-twilightGlass", "Twilight hero barrel / maximum", "", "perfect"],
  ["heroCollapse-twilightGlass", "Twilight hero barrel / collapse", "", "danger"],
  ["maxSpeed", "Movement-earned blasting speed", "", "perfect"],
  ["pumpCompression", "ACTION compression"],
  ["pumpRelease", "ACTION release enhancer", "", "perfect"],
  ["powerLine", "Optional readable speed seam", "", "perfect"],
  ["smallAir", "Small air"],
  ["launch", "Medium lip launch"],
  ["hugeAir", "Huge Moon Log air", "", "perfect"],
  ["clockwiseSpin", "Clockwise 360"],
  ["counterSpin", "Counterclockwise 360"],
  ["frontRail", "Held Front Rail Grab"],
  ["tailGrab", "Tail Grab"],
  ["varial", "Board Varial"],
  ["kakiTwist", "Kaki Twist", "", "perfect"],
  ["snap", "On-wave Snap"],
  ["cutback", "On-wave Cutback"],
  ["floater", "On-wave Floater"],
  ["tubeTuck", "Critical Tube Tuck", "", "danger"],
  ["combo360", "360 grab + board trick"],
  ["combo540", "Perfect 540 chain", "", "perfect"],
  ["switchLanding", "Perfect switch landing", "", "perfect"],
  ["perfectLanding", "Perfect landing", "", "perfect"],
  ["wobble", "Wobble recovery", "", "danger"],
  ["wipeout", "Affectionate wipeout", "", "danger"],
  ["dolphinApproach", "Dolphin approach"],
  ["dolphinRide", "Dolphin Ride", "", "perfect"],
  ["dolphinDismount", "Dolphin dismount air", "", "perfect"],
  ["sharkApproach", "Shark telegraph", "", "danger"],
  ["sharkNearMiss", "Shark Thread near miss", "", "perfect"],
  ["sharkCollision", "Shark collision", "", "danger"],
  ["whaleDistant", "Distant whale shadow"],
  ["whaleBreach", "Whale breach", "", "perfect"],
  ["whaleRamp", "Whale swell ramp"],
  ["whaleRide", "Whale Ride", "", "perfect"],
  ["whaleSplash", "Whale impact splash"],
  ["dolphinGates", "Dolphin foam gates", "", "perfect"],
  ["dolphinReduced", "Dolphin / Reduced Motion", "", "access"],
  ["sharkHighContrast", "Shark / High Contrast", "", "access"],
  ["whaleReduced", "Whale / Reduced Motion", "", "access"],
  ["ambientBusy", "Three-layer ambient pass", "wide"],
  ["ambientReverse", "Direction-aware reverse parallax", "wide"],
  ["twilightTraffic-twilightGlass", "Twilight condition traffic", "wide"],
  ["stormTraffic-stormbreak", "Storm condition traffic", "wide", "danger"],
  ["gullFlock", "Gull flock"],
  ["pelican", "Pelican near flyby"],
  ["ternFlock", "Tern bank"],
  ["cormorantFlock", "Cormorant dive"],
  ["flockScatter", "Startled flock scatter"],
  ["featherThread", "Harmless Feather Thread", "", "perfect"],
  ["pelicanCourier", "Pelican Mango courier", "", "perfect"],
  ["gullCourier", "Gull Star Foam courier", "", "perfect"],
  ["bannerPlane", "Live-text banner plane"],
  ["bannerBigAir", "Reactive BIG AIR banner"],
  ["bannerDolphins", "Reactive DOLPHINS banner"],
  ["bannerShark", "Reactive SHARK WATCH banner", "", "danger"],
  ["propPlane", "Prop plane"],
  ["helicopter", "Helicopter"],
  ["seaplane", "Seaplane"],
  ["sailboat", "Sailboat"],
  ["speedboat", "Speedboat"],
  ["fishingBoat", "Fishing boat"],
  ["tugboat", "Tugboat"],
  ["cargoShip", "Cargo ship"],
  ["jetSki", "Jet ski"],
  ["rescueCraft", "Storm rescue craft"],
  ["speedboatRace", "Speedboat wake race", "", "perfect"],
  ["jetSkiRace", "Jet-ski wake race", "", "perfect"],
  ["mangoRush", "Mango Rush and HUD cue", "", "perfect"],
  ["moonPop", "Moon Pop and HUD cue", "", "perfect"],
  ["starFoam", "Star Foam and HUD cue", "", "perfect"],
  ["powerupMiss", "Harmless missed powerup"],
  ["planeDrop", "Aircraft powerup drop"],
  ["aircraftDrop", "Telegraphed parachute drop"],
  ["mangoExpired", "Mango Rush expiration cue"],
  ["moonConsumed", "Moon Pop consumption cue"],
  ["starSave", "Star Foam collision save", "", "perfect"],
  ["carrierHaze", "Carrier haze arrival"],
  ["carrierArrival", "Carrier arrival"],
  ["carrierDeck", "Carrier deck activity"],
  ["carrierLaunch", "Carrier aircraft launch"],
  ["fleetAirshow", "Fleet Airshow", "wide", "perfect"],
  ["touch", "Simple touch controls", "wide", "access"],
  ["touchAdvanced", "Advanced touch controls", "wide", "access"],
  ["highContrast", "High Contrast", "", "access"],
  ["reducedMotion", "Reduced Motion", "", "access"],
  ["reducedFlash", "Reduced Flash", "", "access"],
  ["goldenCoast", "Golden Coast environment"],
  ["twilightGlass", "Twilight Glass environment"],
  ["stormbreak", "Stormbreak environment", "", "danger"],
  ["foamPuff-goldenCoast", "Foam Puff / Golden Coast"],
  ["foamPuff-twilightGlass", "Foam Puff / Twilight Glass"],
  ["foamPuff-stormbreak", "Foam Puff / Stormbreak", "", "danger"],
  ["mangoFish-goldenCoast", "Mango Fish / Golden Coast"],
  ["mangoFish-twilightGlass", "Mango Fish / Twilight Glass"],
  ["mangoFish-stormbreak", "Mango Fish / Stormbreak", "", "danger"],
  ["moonLog-goldenCoast", "Moon Log / Golden Coast"],
  ["moonLog-twilightGlass", "Moon Log / Twilight Glass"],
  ["moonLog-stormbreak", "Moon Log / Stormbreak", "", "danger"],
];

const grid = document.querySelector("#qa-grid");
const fragment = document.createDocumentFragment();

for (const [scene, label, size = "", tone = ""] of SCENES) {
  const figure = document.createElement("figure");
  figure.dataset.scene = scene;
  if (size) figure.className = size;
  if (tone) figure.dataset.tone = tone;

  const caption = document.createElement("figcaption");
  caption.textContent = label;

  const shot = document.createElement("img");
  shot.className = "qa-shot";
  shot.loading = "eager";
  shot.decoding = "sync";
  shot.alt = `${label} QA capture`;
  shot.src = `./docs/images/qa/${encodeURIComponent(scene)}.png`;

  figure.append(caption, shot);
  fragment.append(figure);
}

grid.append(fragment);
