const SCENES = [
  ["coreSurfLab", "Core Surf Lab / live deterministic line"],
  ["menu", "Production menu and board cards", "wide"],
  ["results", "Results and run highlights", "wide"],
  ["settingsSimple", "Settings / Simple selected", "wide", "access"],
  ["settingsAdvanced", "Settings / Advanced selected", "wide", "access"],
  ["menu-kakiLand", "Kaki-Land / selected condition card", "wide", "perfect"],
  ["results-kakiLand", "Kaki-Land / Relay results", "wide", "perfect"],
  ["simpleKeyboard", "Simple Controls / keyboard", "wide", "access"],
  ["simpleGamepad", "Simple Controls / gamepad", "wide", "access"],
  ["neutral", "Neutral right-hand ride"],
  ["leftTravel", "Left travel / switch stance"],
  ["rightTravel", "Right travel"],
  ["downhillRight", "Wake / downhill right", "", "perfect"],
  ["downhillLeft", "Wake / downhill left", "", "perfect"],
  ["uphill", "Wake / carried climb"],
  ["reversal", "Committed deep cutback", "", "perfect"],
  ["downhill", "Downhill tuck / physical speed", "", "perfect"],
  ["curlEarly", "Incoming curl / early darkening"],
  ["curlFolding", "Incoming curl / folding lip"],
  ["curlImpact", "Incoming curl / foam impact", "", "danger"],
  ["curlDanger", "Incoming curl / close danger", "", "danger"],
  ["heroGather-twilightGlass", "Twilight travelling break / gather"],
  ["heroPitch-twilightGlass", "Twilight travelling break / pitch"],
  ["heroOpen-twilightGlass", "Twilight travelling break / pour", "", "perfect"],
  ["heroDeep-twilightGlass", "Twilight travelling break / deep", "", "perfect"],
  ["heroMax-twilightGlass", "Twilight travelling break / maximum", "", "perfect"],
  ["heroCollapse-twilightGlass", "Twilight travelling break / collapse", "", "danger"],
  ["heroTube-twilightGlass", "Twilight / rideable tube pocket", "", "perfect"],
  ["heroAir-twilightGlass", "Twilight / rider-only big-air frame", "", "perfect"],
  ["initialRide-kakiLand", "Kaki-Land / initial ride"],
  ["artists-kakiLand", "Kaki-Land / Kemonokaki-maintained artist network", "wide"],
  ["plushers-kakiLand", "Kaki-Land / licensed-reference plush gallery", "wide", "perfect"],
  ["rainbowSeam-kakiLand", "Kaki-Land / complete five-band seam", "", "perfect"],
  ["leftTravel-kakiLand", "Kaki-Land / left travel"],
  ["rightTravel-kakiLand", "Kaki-Land / right travel"],
  ["cutback-kakiLand", "Kaki-Land / committed cutback", "", "perfect"],
  ["turbo-kakiLand", "Kaki-Land / Turbo signal", "", "perfect"],
  ["smallAir-kakiLand", "Kaki-Land / small aerial"],
  ["mediumAir-kakiLand", "Kaki-Land / medium cloud aerial", "", "perfect"],
  ["hugeAir-kakiLand", "Kaki-Land / huge aerial", "", "perfect"],
  ["aerialCloud-kakiLand", "Kaki-Land / high-air cloud network", "", "perfect"],
  ["aerialUpper-kakiLand", "Kaki-Land / upper tiled starfield", "", "perfect"],
  ["aerialSpace-kakiLand", "Kaki-Land / The Last Relay reveal", "wide", "perfect"],
  ["lastRelay-kakiLand", "The Last Relay / notice deform settle reaction", "wide", "perfect"],
  ["relayStart-kakiLand", "Webring Relay / three links open", "", "perfect"],
  ["relayStartLeft-kakiLand", "Webring Relay / left-travel links", "", "perfect"],
  ["relayGate1-kakiLand", "Webring Relay / first drawing received", "", "perfect"],
  ["relayGate2-kakiLand", "Webring Relay / second drawing received", "", "perfect"],
  ["relayGate3-kakiLand", "Webring Relay / ring closed", "", "perfect"],
  ["relayComplete-kakiLand", "Webring Relay / mural and Approval", "wide", "perfect"],
  ["dolphin-kakiLand", "Kaki-Land / dolphin interaction", "", "perfect"],
  ["shark-kakiLand", "Kaki-Land / shark near miss", "", "danger"],
  ["wipeout-kakiLand", "Kaki-Land / wipeout", "", "danger"],
  ["recovery-kakiLand", "Kaki-Land / damp recovery"],
  ["lateEndless-kakiLand", "Kaki-Land / late Endless signal convergence", "wide", "perfect"],
  ["scoreFinal-kakiLand", "Kaki-Land / Score Attack final stretch", "wide", "perfect"],
  ["relayHighContrast-kakiLand", "Kaki-Land Relay / High Contrast", "", "access"],
  ["relayReduced-kakiLand", "Kaki-Land Relay / Reduced Motion", "", "access"],
  ["relayMobile-kakiLand", "Kaki-Land Relay / forced Mobile quality", "", "access"],
  ["maxSpeed", "Movement-earned blasting speed", "", "perfect"],
  ["turboBoost", "Trick-recharged Turbo Boost", "", "perfect"],
  ["pumpCompression", "ACTION compression"],
  ["pumpRelease", "ACTION release enhancer", "", "perfect"],
  ["powerLine", "Optional readable speed seam", "", "perfect"],
  ["smallAir", "Small air"],
  ["launch", "Medium lip launch"],
  ["hugeAir", "Huge Moon Log air", "", "perfect"],
  ["aerialCoast-goldenCoast", "Golden Coast / coastal sky"],
  ["aerialCloud-goldenCoast", "Golden Coast / cloud layer", "", "perfect"],
  ["aerialUpper-goldenCoast", "Golden Coast / upper atmosphere", "", "perfect"],
  ["aerialSpace-goldenCoast", "Golden Coast / Kaki Space", "", "perfect"],
  ["aerialReentry-goldenCoast", "Orbital re-entry / landing indicator", "", "danger"],
  ["aerialCoast-twilightGlass", "Twilight Glass / coastal sky"],
  ["aerialCloud-twilightGlass", "Twilight Glass / cloud layer", "", "perfect"],
  ["aerialUpper-twilightGlass", "Twilight Glass / upper atmosphere", "", "perfect"],
  ["aerialSpace-twilightGlass", "Twilight Glass / Kaki Space", "", "perfect"],
  ["aerialReentry-twilightGlass", "Twilight Glass / atmospheric re-entry", "", "danger"],
  ["aerialCoast-stormbreak", "Stormbreak / storm interior", "", "danger"],
  ["aerialCloud-stormbreak", "Stormbreak / thunderhead climb", "", "danger"],
  ["aerialUpper-stormbreak", "Stormbreak / above the storm", "", "perfect"],
  ["aerialSpace-stormbreak", "Stormbreak / stars over lightning", "", "perfect"],
  ["aerialReentry-stormbreak", "Stormbreak / atmospheric re-entry", "", "danger"],
  ["clockwiseSpin", "Clockwise 360"],
  ["counterSpin", "Counterclockwise 360"],
  ["frontRail", "Held Front Rail Grab"],
  ["tailGrab", "Tail Grab"],
  ["varial", "Board Varial"],
  ["kakiTwist", "Kaki Twist", "", "perfect"],
  ["snap", "On-wave Snap"],
  ["cutback", "On-wave Cutback"],
  ["floater", "On-wave Floater"],
  ["tubeTuck", "Critical Tube Tuck", "", "danger"],
  ["combo360", "360 grab + board trick"],
  ["combo540", "Perfect 540 chain", "", "perfect"],
  ["switchLanding", "Perfect switch landing", "", "perfect"],
  ["perfectLanding", "Perfect landing", "", "perfect"],
  ["wobble", "Wobble recovery", "", "danger"],
  ["wipeout", "Affectionate wipeout", "", "danger"],
  ["dolphinApproach", "Dolphin approach"],
  ["dolphinRide", "Dolphin Ride", "", "perfect"],
  ["dolphinDismount", "Dolphin dismount air", "", "perfect"],
  ["sharkApproach", "Shark telegraph", "", "danger"],
  ["sharkNearMiss", "Shark Thread near miss", "", "perfect"],
  ["sharkCollision", "Shark collision", "", "danger"],
  ["whaleDistant", "Distant whale shadow"],
  ["whaleBreachStart", "Whale breach / water takeoff", "", "perfect"],
  ["whaleBreach", "Whale breach", "", "perfect"],
  ["whaleBreachReturn", "Whale breach / water return", "", "perfect"],
  ["whaleRamp", "Whale swell ramp"],
  ["whaleRide", "Whale Ride", "", "perfect"],
  ["whaleRideLeft", "Whale Ride / Left", "", "perfect"],
  ["whaleSplash", "Whale impact splash"],
  ["dolphinGates", "Dolphin foam gates", "", "perfect"],
  ["dolphinReduced", "Dolphin / Reduced Motion", "", "access"],
  ["sharkHighContrast", "Shark / High Contrast", "", "access"],
  ["whaleReduced", "Whale / Reduced Motion", "", "access"],
  ["ambientBusy", "Three-layer ambient pass", "wide"],
  ["ambientReverse", "Direction-aware reverse parallax", "wide"],
  ["twilightTraffic-twilightGlass", "Twilight condition traffic", "wide"],
  ["stormTraffic-stormbreak", "Storm condition traffic", "wide", "danger"],
  ["gullFlock", "Gull flock"],
  ["pelican", "Pelican near flyby"],
  ["ternFlock", "Tern bank"],
  ["cormorantFlock", "Cormorant dive"],
  ["flockScatter", "Startled flock scatter"],
  ["featherThread", "Harmless Feather Thread", "", "perfect"],
  ["pelicanCourier", "Pelican Mango courier", "", "perfect"],
  ["gullCourier", "Gull Star Foam courier", "", "perfect"],
  ["bannerPlane", "Live-text banner plane"],
  ["bannerBigAir", "Reactive BIG AIR banner"],
  ["bannerDolphins", "Reactive DOLPHINS banner"],
  ["bannerShark", "Reactive SHARK WATCH banner", "", "danger"],
  ["propPlane", "Prop plane"],
  ["helicopter", "Helicopter"],
  ["seaplane", "Seaplane"],
  ["sailboat", "Sailboat"],
  ["speedboat", "Speedboat"],
  ["fishingBoat", "Fishing boat"],
  ["tugboat", "Tugboat"],
  ["cargoShip", "Cargo ship"],
  ["jetSki", "Jet ski"],
  ["rescueCraft", "Storm rescue craft"],
  ["speedboatRace", "Speedboat wake race", "", "perfect"],
  ["jetSkiRace", "Jet-ski wake race", "", "perfect"],
  ["mangoRush", "Mango Rush and HUD cue", "", "perfect"],
  ["moonPop", "Moon Pop and HUD cue", "", "perfect"],
  ["starFoam", "Star Foam and HUD cue", "", "perfect"],
  ["powerupMiss", "Harmless missed powerup"],
  ["planeDrop", "Aircraft powerup drop"],
  ["aircraftDrop", "Telegraphed parachute drop"],
  ["mangoExpired", "Mango Rush expiration cue"],
  ["moonConsumed", "Moon Pop consumption cue"],
  ["starSave", "Star Foam collision save", "", "perfect"],
  ["carrierHaze", "Carrier haze arrival"],
  ["carrierArrival", "Carrier arrival"],
  ["carrierDeck", "Carrier deck activity"],
  ["carrierLaunch", "Carrier aircraft launch"],
  ["fleetAirshow", "Fleet Airshow", "wide", "perfect"],
  ["touch", "Simple touch controls", "wide", "access"],
  ["touchAdvanced", "Advanced touch controls", "wide", "access"],
  ["highContrast", "High Contrast", "", "access"],
  ["reducedMotion", "Reduced Motion", "", "access"],
  ["reducedFlash", "Reduced Flash", "", "access"],
  ["goldenCoast", "Golden Coast environment"],
  ["twilightGlass", "Twilight Glass environment"],
  ["stormbreak", "Stormbreak environment", "", "danger"],
  ["kakiLand", "Kaki-Land environment", "", "perfect"],
  ["foamPuff-goldenCoast", "Foam Puff / Golden Coast"],
  ["foamPuff-twilightGlass", "Foam Puff / Twilight Glass"],
  ["foamPuff-stormbreak", "Foam Puff / Stormbreak", "", "danger"],
  ["foamPuff-kakiLand", "Foam Puff / Kaki-Land", "", "perfect"],
  ["mangoFish-goldenCoast", "Mango Fish / Golden Coast"],
  ["mangoFish-twilightGlass", "Mango Fish / Twilight Glass"],
  ["mangoFish-stormbreak", "Mango Fish / Stormbreak", "", "danger"],
  ["mangoFish-kakiLand", "Mango Fish / Kaki-Land", "", "perfect"],
  ["moonLog-goldenCoast", "Moon Log / Golden Coast"],
  ["moonLog-twilightGlass", "Moon Log / Twilight Glass"],
  ["moonLog-stormbreak", "Moon Log / Stormbreak", "", "danger"],
  ["moonLog-kakiLand", "Moon Log / Kaki-Land", "", "perfect"],
];

const grid = document.querySelector("#qa-grid");
const fragment = document.createDocumentFragment();

for (const [scene, label, size = "", tone = ""] of SCENES) {
  const figure = document.createElement("figure");
  figure.dataset.scene = scene;
  if (size) figure.className = size;
  if (tone) figure.dataset.tone = tone;

  const caption = document.createElement("figcaption");
  caption.textContent = label;

  const shot = document.createElement("img");
  shot.className = "qa-shot";
  shot.loading = "eager";
  shot.decoding = "sync";
  shot.alt = `${label} QA capture`;
  shot.src = `./docs/images/qa/${encodeURIComponent(scene)}.png`;

  figure.append(caption, shot);
  fragment.append(figure);
}

grid.append(fragment);
